apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../../base/
patches:
  - target:
      kind: Deployment
    path: 'nfs.patch.yaml'
  - target:
      kind: Deployment
    path: 'pull.patch.yaml'