apiVersion: v1
kind: Service
metadata:
  name: variation-graphql-svc
  labels:
     ensembl.variation.api.name: variation-graphql
spec:
  selector:
     ensembl.variation.api.name: variation-graphql
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000