include: '/gitlab-ci-templates/.templates.yml'

# Jobs for webteam deployments
# Job to build docker image
Build:Docker-Image:
  extends: .build

# Job to deploy to the live environment
Live:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
  rules:
    - !reference [.web-rules]
    - !reference [.rules]
  environment:
    name: wp40-hl-prod

# Job to deploy to the live environment
Live:Web:HX:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hx
  rules:
    - !reference [.web-rules]
    - !reference [.rules]
  environment:
    name: wp41-hx-prod

# Job to deploy to staging (web)
Staging:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
  rules:
    - !reference [.web-rules]
    - !reference [.rules]
  environment:
    name: wp40-hl-staging

# Job to deploy to Internal (web)
Internal:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
  rules:
    - !reference [.web-rules]
    - !reference [.rules]
  environment:
    name: wp40-hl-internal

# Job to deploy to dev-2020 (web)
Dev:Web:HL51:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
  rules:
    - !reference [.web-rules]
    - !reference [.rules]
  environment:
    name: wp51-hl-development
