include: '/gitlab-ci-templates/.templates.yml'

# Jobs for webteam deployments
# Job to build docker image
Build:Docker-Image:
  extends: .build
  rules:
    - !reference [.web-rules]

# Job to deploy to the live environment
Live:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
    AGENT: ${PROD_AGENT}
    NS: ${PROD_NS}
  rules:
    - !reference [.web-rules]
  environment:
    name: production

# Job to deploy to the live environment
Live:Web:HX:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hx
    AGENT: ${FALLBACK_AGENT}
    NS: ${FALLBACK_NS}
  rules:
    - !reference [.web-rules]
  environment:
    name: fallback

# Job to deploy to staging (web)
Staging:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
    AGENT: ${STAGING_AGENT}
    NS: ${STAGING_NS}
  rules:
    - !reference [.web-rules]
  environment:
    name: staging

# Job to deploy to Internal (web)
Internal:Web:HL:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
    AGENT: ${INTERNAL_AGENT}
    NS: ${INTERNAL_NS}
  rules:
    - !reference [.web-rules]
  environment:
    name: internal

# Job to deploy to dev-2020 (web)
Dev:Web:HL51:
  extends: .deploy
  variables:
    BASE: k8s/overlays/webteam/hl
    AGENT: ${DEV_AGENT}
    NS: ${DEV_NS}
  rules:
    - !reference [.web-rules]
  environment:
    name: development

